export const GET_USERS_REQUEST='GET_USERS_REQUEST';
export const GET_USERS_SUCCESS='GET_USERS_SUCCESS';
export const GET_USERS_FAILED='GET_USERS_FAILED';

export const SAVE_USER_REQUEST='SAVE_USER_REQUEST';
export const SAVE_USER_SUCCESS='SAVE_USER_SUCCESS';
export const SAVE_USER_FAILED='SAVE_USER_FAILED';

export const DELETE_USER_REQUEST='DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED='DELETE_USER_FAILED';